---
- name: Set fact for environment variables
  set_fact:
    zuul_changes: "{{ lookup('env', 'ZUUL_CHANGES') }}"
    nodes_config: "{{ lookup('env', 'NODES_FILE') }}"
    toci_jobtype: "{{ lookup('env', 'TOCI_JOBTYPE') }}"

- name: Set fact for stable branch
  set_fact:
    stable_release: "{{ lookup('env', 'STABLE_RELEASE') }}"

- name: Create the reproducer file from template
  template:
    src: "{{ reproducer_quickstart_script }}"
    dest: "{{ artcl_collect_dir }}/reproducer-quickstart.sh"
    mode: 0755

- name: Create reproducer script documentation from template
  template:
    src: README-reproducer-quickstart.html.j2
    dest: "{{ reproducer_quickstart_readme_file }}"
