---
- name: Check if collect directory exists
  stat:
    path: "{{ artcl_collect_dir }}"
  register: collect_dir

- name: Create collect directory
  file:
    path: "{{ artcl_collect_dir }}"
    state: directory
  when: not collect_dir.stat.exists

- name: Create the reproducer file from template
  template:
    src: "{{ reproducer_quickstart_script }}"
    dest: "{{ artcl_collect_dir }}/reproducer-quickstart.sh"
    mode: 0755

- name: Create reproducer script documentation from template
  template:
    src: README-reproducer-quickstart.html.j2
    dest: "{{ reproducer_quickstart_readme_file }}"
