# Introspection is disabled because we don't run Ironic in multinode jobs
step_introspect: false

# Define a single controller node and a single compute node.
overcloud_nodes:
  - name: control_0
    flavor: control
    virtualbmc_port: 6230

composable_services: false
deploy_multinode: true
deploy_composable_scenario: true
composable_scenario: scenario004-multinode.yaml

network_isolation: false

# This enables TLS for the undercloud which will also make haproxy bind to the
# configured public-vip and admin-vip.
undercloud_generate_service_certificate: false

# This enables the deployment of the overcloud with SSL.
ssl_overcloud: false

# If `test_tempest` is `true`, run tempests tests, otherwise do not
# run them.
test_ping: true
validate_template: scenario004-multinode.yaml
run_tempest: false
tempest_workers: 4

# TODO (bkero): Add additional log collection for scenario services

# options below direct automatic doc generation by tripleo-collect-logs
artcl_gen_docs: true
artcl_create_docs_payload:
  included_deployment_scripts:
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate
  included_static_docs:
    - env-setup-virt
  table_of_contents:
    - env-setup-virt
    - undercloud-install
    - overcloud-custom-tht-script
    - overcloud-prep-flavors
    - overcloud-prep-images
    - overcloud-prep-network
    - overcloud-deploy
    - overcloud-deploy-post
    - overcloud-validate
