- include: update-cloud-init.yml
  when: enable_tls_everywhere|bool

- include: create-scripts.yml
  tags:
    - undercloud-scripts

- include: overcloud-prep-images.yml
  tags:
    - undercloud-post-install
