# Updates the cloud-init package in the overcloud images, since it's needed for
# novajoin/TlS-everywhere to properly work. This is currently a workaround
# until the fix for https://bugzilla.redhat.com/show_bug.cgi?id=1420946 is
# available in CentOS.

- name: Fetch cloud-init package
  get_url:
    url: http://66.187.229.139/test/cloud-init-0.7.6-9.el7.x86_64.rpm
    dest: "{{ working_dir }}/cloud-init-0.7.6-9.el7.x86_64.rpm"
    mode: 0755

- name: Update cloud-init from the overcloud-full image
  include_role:
    name: modify-image
  vars:
    image_to_modify: "{{ working_dir }}/overcloud-full.qcow2"
    modify_image_upload_files:
      - src: "{{ working_dir }}/cloud-init-0.7.6-9.el7.x86_64.rpm"
        dest: /root/cloud-init-0.7.6-9.el7.x86_64.rpm
    modify_image_install_packages:
      - '/root/cloud-init-0.7.6-9.el7.x86_64.rpm'
