# Conditional facts to be set which are common to undercloud and overcloud
- name: set docker_registry_namespace_used
  set_fact:
    docker_registry_namespace_used: "{{ docker_registry_namespace }}"

- name: set container_build_id from get_build_command
  set_fact:
    container_build_id: "{{ get_build_command }}"
  when: get_build_command is defined

- name: set mixed upgrade container_build_id
  set_fact:
    container_build_id: "{{ overcloud_docker_image_tag }}"
    docker_registry_namespace_used: "{{ overcloud_docker_registry_namespace }}"
  when:
  - container_build_id is not defined
  - use_overcloud_mixed_upgrade|default(false)|bool

- name: set container_build_id from docker_image_tag
  set_fact:
    container_build_id: "{{ docker_image_tag }}"
  when: container_build_id is not defined

- name: Set update_containers_append_tag for the play
  set_fact:
    update_containers_append_tag: "{{ lookup('pipe','date +-updated-%Y%m%d%H%M%S') }}"
  when: update_containers is defined and update_containers|bool and update_containers_append_tag is undefined
