---
- name: Create /opt/stack directory
  file:
    path: /opt/stack
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  become: true

- name: Link /opt/stack/new to /opt/stack for backwards compat
  file:
    src: /opt/stack
    dest: /opt/stack/new
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  become: true

- name: Clone repos
  git:
    repo: "{{ item }}"
    dest: "/opt/stack/{{ item.split('/')[-1] }}"
    version: master
  with_items:
    - https://git.openstack.org/openstack/tripleo-quickstart
    - https://git.openstack.org/openstack/tripleo-quickstart-extras
    - https://git.openstack.org/openstack-infra/tripleo-ci
    - https://git.openstack.org/openstack-dev/devstack
    - https://git.openstack.org/openstack-infra/devstack-gate

- name: Create /opt/cache/files directory
  file:
    path: /opt/cache/files
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  become: true

- name: Download Cirros image
  get_url:
    url: "{{ nodepool_cirros_url }}"
    dest: "{{ nodepool_cirros_dest }}"
    checksum: "{{ nodepool_cirros_checksum }}"
