---
- name: Prepare containers for the undercloud containerized deployment
  shell: >
    set -o pipefail &&
    {{ working_dir }}/undercloud-prep-containers.sh 2>&1 {{ timestamper_cmd }} >
    {{ working_dir }}/undercloud_prep_containers.log
