- name: Deploy the overcloud
  shell: >
    {{ working_dir }}/overcloud-deploy.sh 2>&1 {{ timestamper_cmd }} > {{ deploy_log }}
  register: deploy_script_result
  ignore_errors: True
  when: step_deploy_overcloud
