- when: deploy_steps_ansible_workflow|bool
  block:
    - name: Add subnodes to known hosts
      shell: |
        ssh-keyscan 192.168.24.3 >> ~/.ssh/known_hosts

- name: Deploy the overcloud
  shell: >
    set -o pipefail &&
    {{ working_dir }}/overcloud-deploy.sh 2>&1 {{ timestamper_cmd }} > {{ deploy_log }}
  register: deploy_script_result
  ignore_errors: True
  when: step_deploy_overcloud|bool

- name: Export actual used deploy args for persistence to other plays
  set_fact:
    # deploy_args end with a newline, remove to make deploy_args_used easier to use
    deploy_args_used: "{{ deploy_args | replace('\n', ' ') }}"
