# Create the scripts that will be used to setup the overcloud images

- name: Create overcloud prep-containers script
  template:
    src: "{{ overcloud_prep_containers_script }}"
    dest: "{{ working_dir }}/overcloud-prep-containers.sh"
    mode: 0755
