---
# tasks file for ansible-role-tripleo-overcloud-prep-containers
- include: create-scripts.yml
  tags:
    - undercloud-scripts
  when: release in ['ocata', 'pike', 'queens', 'rocky']

- include: overcloud-prep-containers.yml
  tags:
    - containers
  when: release in ['ocata', 'pike', 'queens', 'rocky']
