---
- when: update_containers|bool
  block:
    - name: check if python setup tool is installed
      shell: command -v easy-install >/dev/null 2>&1
      register: easy_install_exists
      ignore_errors: yes

    - when: easy_install_exists.rc == 1
      name: Install python setuptools
      package:
        name: python-setuptools
        state: latest
      become: true

    - name: easy-install pip
      command: easy_install pip
      become: true

    - name: Update pip
      pip:
        name: pip
        state: latest
        extra_args: --upgrade
      become: true

    - name: Pip install container-check
      pip:
        name: container-check
        state: latest
        extra_args: --upgrade
      become: true

- name: Prepare for the containerized deployment
  shell: >
    set -o pipefail &&
    {{ working_dir }}/{{ overcloud_prep_containers_script }} 2>&1 {{ timestamper_cmd }} >
    {{ overcloud_prep_containers_log }}
  when: containerized_overcloud|bool
