---
- name: Prepare for the containerized deployment
  shell: >
    {{ working_dir }}/overcloud-prep-containers.sh 2>&1 {{ timestamper_cmd }} >
    {{ overcloud_prep_containers_log }}
  when: containerized_overcloud|bool
