---

- name: Install hostname correcting script
  template:
    src: hostname.sh.j2
    dest: "{{ working_dir }}/hostname.sh"
    mode: 0755

- name: Run the hostname correcting script
  shell: >
    set -o pipefail &&
    {{ working_dir }}/hostname.sh 2>&1 {{ timestamper_cmd }} > {{ working_dir }}/hostname.sh.log
