---
- name: Install stackviz
  pip:
    name: "{{ stackviz_tarball }}"
    virtualenv: "{{ working_dir }}/tempest/.stackviz"

- name: Check if dstats file exists
  stat: path=/var/log/extra/dstat-csv.log
  register: dstat_result

- name: Set dstat fact
  set_fact:
      tempest_dstat_opt: '--dstat /var/log/extra/dstat-csv.log'
  when: dstat_result.stat.exists

- name: Set the proper permission for tempest directory and files
  file:
    dest: "{{ working_dir }}/tempest"
    owner: "{{ undercloud_user }}"
    group: "{{ undercloud_user }}"
    recurse: yes
  become: true

- name: Copy stackviz static file to home directory
  shell: >
    cp -r "{{ working_dir }}/tempest/.stackviz/share/stackviz-html" "{{ working_dir }}/stackviz"

- name: Collecting data from tempest
  shell: |
    set -o pipefail
    source "{{ working_dir }}/tempest/.stackviz/bin/activate"
    stackviz-export {{ tempest_dstat_opt | default('') }} --env -f {{ working_dir }}/tempest/testrepository.subunit {{ working_dir }}/stackviz/data
  args:
      chdir: "{{ working_dir }}/tempest"

- name: Moving stackviz to /var/log/extra
  shell: mv {{ working_dir }}/stackviz/ /var/log/extra/stackviz
  become: true
