---
- name: Baremetal undercloud install
  hosts: localhost
  roles:
    - baremetal-undercloud
  tags:
    - baremetal-undercloud

- name: Add the undercloud node to the generated inventory
  hosts: localhost
  gather_facts: yes
  roles:
    - tripleo-inventory
  tags:
    - undercloud-inventory

- name: Setup repositories
  hosts: undercloud
  gather_facts: yes
  roles:
    - repo-setup
  tags:
    - undercloud-repo-setup

- name: Install packages
  hosts: undercloud
  gather_facts: no
  roles:
    - baremetal-undercloud/packages
  tags:
    - undercloud-pkgs-install

- name: Fetch the overcloud images
  hosts: undercloud
  gather_facts: no
  roles:
    - fetch-images
  tags:
    - overcloud-fetch-images
