---
- name: Run inventory to add supplemental node
  hosts: undercloud
  gather_facts: false
  tags:
    - freeipa-setup
  tasks:

    - include_role:
        name: tripleo-inventory
      vars:
        inventory: extra_node

- name: Deploy the FreeIPA server
  hosts: supplemental
  gather_facts: true
  tags:
    - freeipa-setup
  tasks:

    - include_role:
        name: repo-setup
      vars:
        repo_setup_dir: /home/{{ supplemental_user|default('centos') }}

    - include_role:
        name: freeipa-setup
