---
- include: baremetal-prep-virthost.yml
  when: undercloud_type == 'virtual' and environment_type is defined

- include: ovb-setup.yml
  when: undercloud_type == 'ovb'

- include: baremetal-undercloud.yml
  when: undercloud_type == 'baremetal' and environment_type is defined

- include: baremetal-quickstart-extras.yml

- include: overcloud-validate-ha.yml
  when: validate_ha_overcloud is defined and validate_ha_overcloud|bool
