---
- name: Run dump vars on all!localhost
  hosts: all:!localhost:!127.0.0.2
  roles:
    - dump_vars

- name: Collect logs
  hosts: all:!localhost:!127.0.0.2
  roles:
    - collect-logs

- name: Create docs, publish logs
  hosts: localhost
  roles:
    - {role: collect-logs, artcl_collect: false }
