---
- name: Run dump vars on all!localhost
  hosts: all:!localhost:!127.0.0.2
  roles:
    - dump_vars

- name: Run dump vars on localhost
  hosts: localhost
  gather_facts: yes
  roles:
    - { role: dump_vars, dump_vars_log_dir: "{{ local_working_dir }}" }

- name: Collect logs
  hosts: all:!localhost:!127.0.0.2
  roles:
    - collect-logs

- name: Create docs, publish logs
  hosts: localhost
  roles:
    - {role: collect-logs, artcl_collect: false }
