# TODO: This is to keep legacy job compatibility.
# Currently used by P->Q and O->P job.
- name: Overcloud upgrade compatibility mode.  Please switch to tripleo-upgrade role.
  when: not use_tripleo_upgrade|default(false)|bool
  include: multinode-overcloud-upgrade-legacy.yml

# TODO(chem): that glue code part should be in its own role, to keep the
# playbook clean.
- name: Overcloud tripleo-upgrade.
  when: use_tripleo_upgrade|default(false)|bool
  include: multinode-overcloud-upgrade-new.yml

