- name: Run tripleo-upgrade role to update the overcloud
  hosts: undercloud
  gather_facts: yes
  tags:
    - overcloud-update
  roles:
    - role: tripleo-upgrade
      when: overcloud_update|default(false)|bool
