---
- name: setup dstat performance monitoring
  hosts: overcloud
  tags:
    - overcloud-validate
  roles:
    - { role: validate-perf, when: validate_performance|bool }

# Validate the deployment
- name:  validate the overcloud
  hosts: undercloud
  tags:
    - overcloud-validate
    - undercloud-validate
  gather_facts: no
  roles:
    - { role: validate-simple, when: test_ping|bool }
    - { role: validate-tempest, when: run_tempest|bool }
