---
- name: Create the OVB stack
  hosts: localhost
  roles:
    - { role: ovb-manage-stack, ovb_manage_stack_mode: 'create' }

- name: Build test packages using DLRN
  hosts: localhost
  roles:
    - {role: build-test-packages, when: build_test_packages|default(false)|bool }

- name: Setup the undercloud
  hosts: undercloud
  gather_facts: no
  vars:
    ansible_user: root
  roles:
    - undercloud-setup

- name:  Inventory the undercloud instance
  hosts: localhost
  gather_facts: yes
  roles:
    - tripleo-inventory

- name: Install the built package on the undercloud
  hosts: undercloud
  gather_facts: no
  vars:
    ib_repo_host: localhost
  roles:
    - {role: install-built-repo, when: build_test_packages|default(false)|bool }

- name: Fetch the overcloud images
  hosts: undercloud
  gather_facts: no
  vars:
      ansible_user: root
  roles:
   - fetch-images
