---

- name: Configure tripleo-validations
  hosts: undercloud
  gather_facts: no
  tags:
    - tripleo-validations
  vars:
    run_tripleo_validations_setup: True
  roles:
    - { role: tripleo-validations,
        when: run_tripleo_validations|bool or run_tripleo_validations_negative_tests|bool}

- name: Run tripleo-validations pre-introspection tests
  hosts: undercloud
  gather_facts: no
  tags:
    - tripleo-validations
  vars:
    validations_group: ['pre-introspection']
  roles:
    - { role: tripleo-validations,
        when: run_tripleo_validations|bool or run_tripleo_validations_negative_tests|bool}

