---
# Upgrade Undercloud and Overcloud on top of a quickstart Baremetal deployment
- include: baremetal-full-deploy.yml

- name:  Upgrade Tripleo
  hosts: undercloud
  gather_facts: no
  roles:
    - { role: overcloud-upgrade, deployment_type: baremetal }

# Execute sanity checks against the overcloud deployment
- name: Sanity check the overcloud services
  hosts: undercloud
  tags:
    - overcloud-validate
  gather_facts: no
  roles:
    - { role: validate-sanity-checks,
        sanity_checks_log: validate_sanity_checks_upgraded.log,
        when: run_sanity_checks|default(false)|bool }

# Validate the deployment
- name:  validate the overcloud
  hosts: undercloud
  tags:
    - overcloud-validate
  gather_facts: no
  roles:
    - { role: validate-simple, when: test_ping|bool }
