---
- name: Upgrade the overcloud
  shell: >
    set -o pipefail &&
    {{ upgrade_working_dir }}/overcloud-upgrade.sh 2>&1 {{ timestamper_cmd }} >
    {{ upgrade_log }}
  when: step_upgrade_overcloud
